apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer
data:
  application.properties: |
    # Consumer properties
    bootstrap.servers=kafka:29092
    key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
    max.poll.interval.ms=300000
    enable.auto.commit=true
    auto.offset.reset=earliest
    group.id=consumer-application
    
    #Properties below this line are specific to code in this application
    file_path=/mounted-volume/output/out.txt
    consumer_topic_names=input-topic,output-topic
