apiVersion: v1
kind: ConfigMap
metadata:
  name: producer
data:
  application.properties: |
    #Kafka properties
    bootstrap.servers=kafka:29092
    key.serializer=org.apache.kafka.common.serialization.StringSerializer
    value.serializer=org.apache.kafka.common.serialization.StringSerializer
    acks=all
    
    #Properties below this line are specific to code in this application
    input_dir=/mounted-volume/upload
    processed_dir=/mounted-volume/uploaded
    interval_period_ms=10000
    producer_topic_name=input-topic
    
    #user_agent parameter is optional, when not not provided then
    #all user agents being processed
    user_agent=some user agent
