apiVersion: v1
kind: ConfigMap
metadata:
  name: streams
data:
  application.properties: |
    #Kafka properties
    bootstrap.servers=kafka:29092
    key.serializer=org.apache.kafka.common.serialization.StringSerializer
    value.serializer=org.apache.kafka.common.serialization.StringSerializer
    acks=all
    application.id=window-aggregation
    cache.max.bytes.buffering=0
    commit.interval.ms=0
    
    #Properties below this line are specific to code in this application
    input_topic = input-topic
    output_topic = output-topic
    store_name = window-aggregate-store
    window_size = PT1H
    #Examples:
    #"PT20.345S" -- parses as "20.345 seconds"
    #"PT15M"     -- parses as "15 minutes" (where a minute is 60 seconds)
    #"PT10H"     -- parses as "10 hours" (where an hour is 3600 seconds)
    #"P2D"       -- parses as "2 days" (where a day is 24 hours or 86400 seconds)
    #"P2DT3H4M"  -- parses as "2 days, 3 hours and 4 minutes"
    #"P-6H3M"    -- parses as "-6 hours and +3 minutes"
    #"-P6H3M"    -- parses as "-6 hours and -3 minutes"
    #"-P-6H+3M"  -- parses as "+6 hours and -3 minutes"
