apiVersion: apps/v1
kind: Deployment
metadata:
  name: streams
  labels:
    app: streams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streams
  template:
    metadata:
      labels:
        app: streams
    spec:
      containers:
      - name: streams
        image: lukaszgendek/big_data_homework:kafka-streams
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
        volumeMounts:
        - name: configuration
          mountPath: /configuration
        env:
          - name: CONFIG_FILE
            value: /configuration/application.properties
      volumes:
      - name: configuration
        configMap: 
          name: streams
          items:
            - key: application.properties
              path: application.properties
